#!/bin/bash
DEBUG=false
if [[ "$*" == *"--debug"* ]]; then
    DEBUG=true
fi
VERSION=4

# Check for version option
if [[ "$*" == *"-v"* ]] || [[ "$*" == *"--version"* ]]; then
    echo "$VERSION"
    exit 0
fi

# Define paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

if [ $DEBUG = true ]; then
    LOGS_DIR="$SCRIPT_DIR/logs"
else
    LOGS_DIR="/Library/Application Support/UptimeLogger"
fi

LOG_LATEST="$LOGS_DIR/latest"
CONFIG_FILE="$LOGS_DIR/config"
if [[ ! -d "$LOGS_DIR" ]]; then
    mkdir "$LOGS_DIR"
fi
chmod -R 766 "$LOGS_DIR"
chmod 777 "$LOGS_DIR"

# Allowed Shutdown Features
UPDATE_FILE="$LOGS_DIR/updated"
SHUTDOWN_FILE="$LOGS_DIR/shutdown"

# Allow Shutdown Script
if [[ "$*" == *"-s"* ]] || [[ "$*" == *"--allow-shutdown"* ]]; then
    touch "$SHUTDOWN_FILE"
    chmod 766 "$SHUTDOWN_FILE"
    exit 0
fi

function allowShutdown() {
    echo "shutdown allowed" >>"$LOG_LATEST"
    rm "$SHUTDOWN_FILE"
    rm "$LOG_LATEST"
}
if test -f "$SHUTDOWN_FILE" && test -f "$LOG_LATEST"; then
    allowShutdown
fi

# Registra a data e hora de inicialização
if [ -f "$UPDATE_FILE" ]; then
    STARTUP="$(cat "$UPDATE_FILE")"
    rm "$UPDATE_FILE"
    echo "Continuing from update of $STARTUP"
else
    STARTUP="$(date +"%Y-%m-%d_%H-%M-%S")"
fi

# Set log files names
LOG_FILE="$LOGS_DIR/log_$STARTUP.txt"
PLOG_FILE="$LOGS_DIR/log_$STARTUP.log"
if [ ! -f "$LOG_FILE" ]; then
    echo "version: $VERSION"$'\n' > "$LOG_FILE"
fi

ln -sf "$LOG_FILE" "$LOG_LATEST"

# Verifica se o modo de depuração está habilitado
if [[ "$*" == *"--debug"* ]]; then
    echo ""
    echo "OSTYPE: $OSTYPE"
    echo "SCRIPT_DIR: $SCRIPT_DIR"
    echo "LOGS_DIR: $LOGS_DIR"
    echo "LOG_LATEST: $LOG_LATEST"
    echo "LOG_FILE: $LOG_FILE"
    echo "PLOG_FILE: $PLOG_FILE"
    echo "STARTUP: $STARTUP"
fi

if [ $DEBUG = true ] && [[ "$*" == *"--exit-with-update"* ]]; then
    function finishwithUpdate() {
        echo "$STARTUP" > "$UPDATE_FILE"
        cat "$UPDATE_FILE"
        exit
    }
    trap finishwithUpdate INT TERM
else
    trap "allowShutdown; exit;" INT TERM
fi

# LOG V4
# version: [0-9]+
# init: %Y-%m-%d_%H-%M-%S
# ended: %Y-%m-%d_%H-%M-%S
# sysversion: String
# batery: [0-9]+%
# charging: true/false
# boottime: [0-9]+ (timestamp)
# uptime: [0-9]+ (seconds interval)
# logprocessinterval: [0-9]+
# logprocess: true/false

# Loop infinito para atualizar o uptime a cada 5 minutos
COUNT=0
while true; do

    LOG="version: $VERSION"$'\n'
    LOG+="ended: $(date +"%Y-%m-%d_%H-%M-%S")"$'\n'

    # Verifica o tipo de sistema operacional
    if [[ "$OSTYPE" == "darwin"* ]]; then
        kernelboottime=$(sysctl -n kern.boottime)
        boottimestamp=$(echo $kernelboottime | sed 's/^.*sec = \([0-9]*\), usec.*$/\1/')
        currenttimestamp=$(date +%s)
        elapsedtime=$((currenttimestamp - boottimestamp))
        battery=$(pmset -g batt)

        LOG+="sysversion: $(sw_vers -productVersion)"$'\n'
        LOG+="batery: $(echo "$battery" | grep -Eo '[0-9]+%')"$'\n'
        if echo "$battery" | grep -q "discharging"; then
            LOG+="charging: false"$'\n'
        else
            LOG+="charging: true"$'\n'
        fi

        LOG+="boottime: $boottimestamp"$'\n'
        LOG+="uptime: $elapsedtime"$'\n'
    else
        # Define o comando para obter o tempo de inicialização no Linux
        UPTIME=$(uptime -p)

        LOG+="lastrecord: $UPTIME"$'\n'
    fi

    LOGPROCESS=false
    if [ -r "$CONFIG_FILE" ]; then
        EACHSEC=$(cat "$CONFIG_FILE")
        if [ $((COUNT % EACHSEC)) -eq 0 ]; then            
            ps -ax -o user,pid,pcpu,pmem,start,time,command > "$PLOG_FILE"
            if [ $DEBUG = true ]; then
                echo "logged proceess to file"
            fi
        fi
        LOGPROCESS=true
        LOG+="logprocessinterval: $EACHSEC"$'\n'
    fi
    LOG+="logprocess: $LOGPROCESS"$'\n'

    echo "$LOG" >"$LOG_FILE"

    if [ $DEBUG = true ]; then
        echo "$LOG"
    fi

    sleep 1
    ((COUNT++))
done
