#!/bin/sh

echo "Installer service at $SERVICE_FILE using sudo"

SERVICE_NAME="br.com.victorwads.uptimelogger"
INSTALL_FOLDER="$PKGROOT/Applications/UptimeLogger.app"
SERVICE_FILE="/Library/LaunchDaemons/$SERVICE_NAME.plist"
SERVICE_PLIST=$(cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
   <key>Label</key>
   <string>$SERVICE_NAME</string>
   <key>ProgramArguments</key>
   <array>
      <string>$INSTALL_FOLDER/Contents/Resources/Service/uptime_logger</string>
   </array>
   <key>KeepAlive</key>
   <true/>
</dict>
</plist>
EOF
)

if [ -f "/Library/LaunchDaemons/$SERVICE_NAME.plist" ]; then
    sudo launchctl unload "/Library/LaunchDaemons/$SERVICE_NAME.plist"
    sudo rm "/Library/LaunchDaemons/$SERVICE_NAME.plist"
fi

LAST_LOG_LINK="$INSTALL_FOLDER/Contents/Resources/Service/logs/latest"
if [ -f "$LAST_LOG_LINK" ]; then
    UPDATE_FILE="$INSTALL_FOLDER/Contents/Resources/Service/logs/updated"

    LASTLOGFILE="$(readlink "$LAST_LOG_LINK")"
    FILENAME=$(basename "$LASTLOGFILE" _*.txt)
    LATEST_STARTUP="${FILENAME#*_}"
    LATEST_STARTUP="${LATEST_STARTUP%.txt}"
    echo "$LATEST_STARTUP" > "$UPDATE_FILE"
fi

echo "Installer service at $SERVICE_FILE using sudo"
echo "$SERVICE_PLIST" | sudo tee "$SERVICE_FILE" >/dev/null

# LOGSDIR="/Library/Application Support/UptimeLogger/"
# if [ ! -d "$LOGSDIR" ]; then
#     mkdir "$LOGSDIR"
#     chmod 777 "$LOGSDIR"
# fi

sudo launchctl load "/Library/LaunchDaemons/$SERVICE_NAME.plist"
